### ISSUE TITLE
you forgot package.json

### ISSUE THREAD

**Issue by StoneCypher** [fifikobayashi/Aggregated-Flashloan#1]
someone on reddit wanted to know why they couldn't `npm install` something

it's because you didn't put `package.json` into the repo (though `package-lock` is there)

**Comment by StoneCypher** [comment]
Reference: https://www.reddit.com/r/node/comments/iy96vb/what_is_going_on_here_all_im_trying_to_do_is_run/

**Comment by andermarce** [comment]
@StoneCypher you can create with command: npm init 
and that's it! This work for me.

**Comment by fifikobayashi** [comment]
Thanks for the heads up, I have added a package.json to the repo now.
The project was created via truffle init so the node_modules were there already without the presence of a package.json, hence the absence of one in the initial upload.

**Comment by StoneCypher** [comment]
@andermarce - sorry, no, that's not how this works.  If I create my own package, I get none of the author's scripts, wrong versions of deps, et cetera.

**Comment by StoneCypher** [comment]
@fifikobayashi - high class response, extremely fast fix.  Thanks kindly
